drop table if exists emr_medical_org;
create table emr_medical_org(
    id varchar(50) not null comment '主键',
    workUnitName varchar(100) comment '工作单位名称',
    addrCategoryCode varchar(100) comment '标识地址类别的代码',
    addrprovince varchar(100) comment '地址-省（自治区、直辖市）',
    addrCity varchar(100) comment '地址-市（地区）',
    addrDistrict varchar(100) comment '地址-县（区）',
    addrSubdistrict varchar(100) comment '地址-乡（镇、街道办事处）',
    addrVillage varchar(100) comment '地址-村（街、路、弄等）',
    addrNumber varchar(100) comment '地址-门牌号码',
    zipCode varchar(100) comment '邮政编码',
    divisionCode varchar(100) comment '行政区划代码',
    phoneCategory varchar(100) not null comment '联系电话-类别',
    phoneCategoryCode varchar(100) not null comment '联系电话-类别代码',
    phoneNumber varchar(100) not null comment '联系电话-号码',
    email varchar(100) not null comment '电子邮件地址',
    orgName varchar(100) comment '机构名称',
    orgCode varchar(100) comment '机构组织机构代码',
    orgCharge varchar(100) comment '机构负责人（法人）',
    orgAddress varchar(100) comment '机构地址',
    departName varchar(100) comment '科室名称',
    orgRole varchar(100) comment '机构角色',
    orgRoleCode varchar(100) comment '机构角色代码',
    servicerName varchar(100) comment '服务者姓名',
    servicerRole varchar(100) comment '服务者职责（角色）',
    servicerRoleCode varchar(100) comment '服务者职责（角色）代码',
    servicerMajorSkillDuty varchar(100) comment '服务者专业技术职务',
    servicerEducBackground varchar(100) comment '服务者学历',
    servicerMajor varchar(100) comment '服务者所学专业',
    servicerMajorSkillDutyRank varchar(100) comment '服务者专业技术职务',
    servicerDuty varchar(100) comment '服务者职务',
    primary key(id)
)Engine=InnoDB charset=utf8mb4 comment='医疗机构信息数据集';